id: PB2BC2784
initial_creation_type: ocr
source_metadata:
  volumes:
    b8e6fd995960402799cdf163909bc85d:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: རྡོ་རྗེ་དྲིལ་ཐབས་ཀྱི་མཆོད་པའི་ཐབས་ཀྱི་རིམ་པ།
      total_pages: 2043
      volume_number: 13
