id: D0F440BA8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:05:13+00:00'
last_modified: '2022-05-26T08:09:12.672171+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '7964':
      image_group_id: I1PD95858
      title: རྡོ་རྗེ་དྲིལ་ཐབས་ཀྱི་མཆོད་པའི་ཐབས་ཀྱི་རིམ་པ།
      total_pages: 2043
      order: 13
      base_file: 7964.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
